export { ReactComponent as LogoImage } from './logo.svg'
export { ReactComponent as NotiIcon } from './notification.svg'
export { ReactComponent as SettingIcon } from './setting.svg'
export { ReactComponent as ArrowDownIcon } from './arrow-down.svg'
export { ReactComponent as DashboardIcon } from './menu01.svg'
export { ReactComponent as ManageAdsIcon } from './menu02.svg'
export { ReactComponent as GuideIcon } from './lightbulb.svg'
